<a href="https://colab.research.google.com/github/ucheokechukwu/ml_ztm_projects/blob/main/Pytorch_For_Deep_Learning/00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.udemy.com/course/pytorch-for-deep-learning/

https://www.learnpytorch.io/

https://github.com/mrdbourke/pytorch-deep-learning

 https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


* cuda is what enables us to run pytorch on nvidia gpu

## Introduction to tensors
### creating tensors

pytorch tensors are created using `torch.tensor()`

In [ ]:
# scalar
scalar = torch.tensor(7)
type(scalar), scalar

(torch.Tensor, tensor(7))

In [ ]:
# dimensions
scalar.ndim

0

In [ ]:
scalar.item() # returns regular python integer

7

In [ ]:
# vector
vector = torch.tensor([7,7])
vector.ndim, vector.shape

(1, torch.Size([2]))

In [ ]:
# MATRIX
MATRIX = torch.tensor([[1,2],
                       [3,4]])
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [ ]:
MATRIX[0], MATRIX[:,1]

(tensor([1, 2]), tensor([2, 4]))

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

In [ ]:
TENSOR.ndim, TENSOR.shape, TENSOR.size()

(3, torch.Size([1, 3, 3]), torch.Size([1, 3, 3]))

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### random tensors
-> are important because any neural networks start with tensors full of random numbers and adjust those numbers to represent data.


In [ ]:
# create a random tensor of size ()
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4261, 0.9887, 0.4158, 0.6690],
        [0.6109, 0.4836, 0.1277, 0.0475],
        [0.8411, 0.0492, 0.9971, 0.6669]])

In [ ]:
random_tensor.shape, random_tensor.ndim

(torch.Size([3, 4]), 2)

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # (height, width, color_channels)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
### zeros and ones
zero = torch.zeros(3,4) # size is the default, not always necessary
ones = torch.ones(3,4)

In [ ]:
# data type
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### creating a range of tensors and tensors-like

In [ ]:
torch.range(0,10) # will be deprecated

<ipython-input-28-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.zeros_like(random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### tensor datatypes

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
sample_tensor = torch.tensor([3.0, 6.0, 9.0],
                             dtype=torch.float16, # datatype
                             device='cpu', # what device your tensor is on
                             requires_grad=False, # track the gradient or not
                             )

In [ ]:
sample_tensor.dtype

torch.float16

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [ ]:
float_16_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [ ]:
(float_16_tensor + float_32_tensor).dtype

torch.float32

### getting information from tensors

1. `tensor.dtype`
2. `tensor.shape` or `tensor.size()`
3. `tensor.device`

In [ ]:
some_tensor = torch.rand(1, 2, 3)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device of tensor: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([1, 2, 3])
Shape of tensor: torch.Size([1, 2, 3])
Device of tensor: cpu


In [ ]:
value = 0
TENSOR = torch.rand(100,100)

In [ ]:
%%time
for i in range(len(TENSOR)):
    value += TENSOR[i]*TENSOR[i]
print(value)

tensor([35.0756, 34.6710, 27.8462, 35.6701, 39.4822, 31.2449, 32.2601, 33.5110,
        39.5095, 36.9772, 32.3234, 32.5114, 36.7688, 36.3153, 32.9478, 27.8740,
        37.3854, 37.8943, 33.3980, 35.7211, 29.5981, 37.5334, 31.4266, 33.2985,
        29.7888, 33.5550, 37.8571, 38.9838, 35.2894, 35.0141, 29.3263, 30.2602,
        28.6063, 32.9635, 34.1178, 34.7883, 33.2158, 33.4184, 29.6854, 36.0802,
        29.8497, 38.8075, 39.7099, 35.2240, 30.9138, 31.0973, 35.4649, 37.2106,
        38.1630, 35.8960, 33.4808, 27.4824, 29.1266, 31.7936, 29.8398, 34.1059,
        34.1745, 32.6577, 34.2197, 32.1896, 29.1146, 30.0053, 32.4488, 30.7499,
        30.1204, 29.8067, 35.2643, 33.5797, 37.5174, 33.3224, 37.1559, 35.2250,
        31.3430, 35.6510, 30.1394, 27.6526, 31.0485, 29.9983, 33.4660, 38.3383,
        34.3207, 35.9529, 32.6129, 36.2115, 33.4878, 35.2643, 29.9056, 32.3269,
        30.6490, 33.1576, 37.8627, 30.3430, 35.4947, 35.1427, 35.3609, 31.9576,
        30.1284, 29.5122, 26.4932, 29.41

In [ ]:
%%time
torch.matmul(TENSOR, TENSOR)

CPU times: user 1.76 ms, sys: 0 ns, total: 1.76 ms
Wall time: 19.1 ms


tensor([[21.1962, 23.5096, 20.7004,  ..., 20.6085, 19.2536, 20.1530],
        [23.9283, 25.2402, 21.3751,  ..., 23.8481, 21.9882, 22.5831],
        [22.4826, 23.6433, 21.9274,  ..., 22.8964, 20.3992, 21.3874],
        ...,
        [25.6570, 26.6780, 24.0154,  ..., 23.1339, 22.5019, 24.7663],
        [24.8869, 24.6593, 21.8185,  ..., 22.8127, 21.1809, 22.4388],
        [22.8331, 24.2643, 21.2171,  ..., 21.1568, 19.7577, 21.6927]])

In [ ]:
tensor_a = torch.rand(3,4)
tensor_b = torch.rand(4,3)
torch.mm(tensor_a, tensor_b) # mm is abbreviation of matmul

tensor([[0.9142, 0.8937, 0.4174],
        [1.4659, 1.1980, 0.6694],
        [2.1569, 1.8174, 0.6456]])

In [ ]:
tensor_c=torch.rand(tensor_a.shape)

In [ ]:
torch.mm(tensor_a, tensor_c.T) # .T switches the axis

tensor([[0.8972, 0.7614, 0.4729],
        [1.3340, 1.0064, 0.8131],
        [1.0820, 1.3999, 0.6343]])

### finding the min, max, mean, sum (tensor aggregation)

In [ ]:
x = torch.arange(0,100,10)

In [ ]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [ ]:
x.min(), x.max()

(tensor(0), tensor(90))

In [ ]:
x.dtype

torch.int64

In [ ]:
# torch.mean(x) # will not work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

In [ ]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [ ]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

### reshaping, stacking, squeezing, and unsqueezing
* reshaping - reshapes to a defined shape
view - returns a view in a certain shape but keeps the same memory as the original tensor
* stacking - combines multiple tensors on top of each other(vstack) or side by side (hstack)
* squeeze - removes all 1 dimensions from a tensor
* unsqueeze - addas a 1 dimension to a target tensor
* premute - returns a view of the input with dimensions swapped

In [ ]:
x = torch.arange(1,10)
x_reshape = x.reshape(3,3)

In [ ]:
x_reshape

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x.reshape(9,1,1)

tensor([[[1]],

        [[2]],

        [[3]],

        [[4]],

        [[5]],

        [[6]],

        [[7]],

        [[8]],

        [[9]]])

In [ ]:
z = x.view(3,3)
z.shape, x.shape

(torch.Size([3, 3]), torch.Size([9]))

In [ ]:
# remember view shares the same memory as the original input
z[:,0]=5
z,x

(tensor([[5, 2, 3],
         [5, 5, 6],
         [5, 8, 9]]),
 tensor([5, 2, 3, 5, 5, 6, 5, 8, 9]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x])

In [ ]:
x_stacked

tensor([[5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9]])

In [ ]:
x_stacked = torch.stack([x,x], dim=-1)
x_stacked

tensor([[5, 5],
        [2, 2],
        [3, 3],
        [5, 5],
        [5, 5],
        [6, 6],
        [5, 5],
        [8, 8],
        [9, 9]])

In [ ]:
y = torch.arange(9,0,-1)
x = torch.arange(9)

In [ ]:
torch.stack([x,y], dim=-1), torch.stack([x,y], dim=-2), torch.stack([x,y], dim=0), torch.stack([x,y], dim=1)

(tensor([[0, 9],
         [1, 8],
         [2, 7],
         [3, 6],
         [4, 5],
         [5, 4],
         [6, 3],
         [7, 2],
         [8, 1]]),
 tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8],
         [9, 8, 7, 6, 5, 4, 3, 2, 1]]),
 tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8],
         [9, 8, 7, 6, 5, 4, 3, 2, 1]]),
 tensor([[0, 9],
         [1, 8],
         [2, 7],
         [3, 6],
         [4, 5],
         [5, 4],
         [6, 3],
         [7, 2],
         [8, 1]]))

In [ ]:
x = torch.rand(1,9,2,3)

In [ ]:
x.squeeze().shape

torch.Size([9, 2, 3])

In [ ]:
x.unsqueeze(dim=3).shape

torch.Size([1, 9, 2, 1, 3])

In [ ]:
x.shape

torch.Size([1, 9, 2, 3])

In [ ]:
# torch.permute
torch.permute(x,(2,0,1,3)).shape

torch.Size([2, 1, 9, 3])

In [ ]:
x.permute(2,0,1,3).shape

torch.Size([2, 1, 9, 3])

In [ ]:
# usually used to rearrange image dimensions
x_original = torch.rand(225, 225, 3)
x_original.permute(2,0,1).shape

torch.Size([3, 225, 225])

### Numpy and Torch

In [ ]:
import torch
import numpy as np
array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
type(array), type(tensor)

(numpy.ndarray, torch.Tensor)

In [ ]:
# tensor to numpy
tensor = torch.ones(7,1)
numpy_tensor = tensor.numpy()
numpy_tensor.dtype

dtype('float32')

* numpy default is float64, and the default of pytorch is float32

## reproducibility

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_a = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED) # you have to set it each time before you call the rand
random_b = torch.rand(3,4)
random_a==random_b

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## running tensors or pytorch objects on GPUs to make faster computations

- getting a GPU
- use your own GPU
- use cloud computing (GCP, AWS, Azure, etc)

In [ ]:
import torch
torch.cuda.is_available()

False

In [ ]:
# set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# count number of devices
torch.cuda.device_count()

0

It's best practice to set up device agnostic code. Check out best practices for using cuda:
https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code

### putting tensors (and models) on GPU

* use `.to(device)` method to change the device type

* might need to move tensors back to cpu to, for example, work with numpy which only runs on cpu

In [ ]:
import torch
# set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device
tensor = torch.tensor([1,2,3])

## by default the tensor is on the cpu
# tensornot on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# if tensor is on gpu, cannot transform to numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])

In [ ]:
tensor_on_gpu.to('cpu').numpy() # also works

array([1, 2, 3])